version: "3"
services:
  db:
    container_name: db
    image: mongo:4.0
    restart: always
    ports:
      - '27017:27017'

  web:
    image:
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: "/ansible/scripts/run-ansible.sh"




